version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.24
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-163-246-159.compute-1.amazonaws.com
            database: deg7kqnofm6af8
            ssl: true
            user: jhhutvgmonohsq
            password: 86564991cd70bf1f1ec46157c4acf6858e58173a142b4a87a5431470ef993b3f
            rawAccess: true
            port: '5432'
            migrations: true